version: '3'

services:
  app:
    build:
      context: ./flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app/app:/app
    working_dir: /app
    environment:
      - ENV=development
    depends_on:
      - ollama
    networks:
      - recipe

  ollama:
    image: ollama/ollama
    ports:
      - "5001:5001"
    volumes:
      - ollama-models:/root/.ollama/models
    environment:
      - ENV=development
    networks:
      - recipe

volumes:
  ollama-models:

networks:
  recipe:
