# Use the official Ollama image
FROM ollama/ollama

# Make port 11434 available to the world outside this container
EXPOSE 11434

CMD ["ollama", "pull", "llama3"]

# Command to run when the container starts
CMD ["ollama", "run", "llama3"]
