# Use the official Ollama image
FROM ollama/ollama

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Command to run when the container starts
CMD ["ollama", "run", "llama3"]
