version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Mount local ./app directory to /app in the container
    working_dir: /app  # Set working directory to /app
    environment:
      - ENV=development

